version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./.docker/rufans/Dockerfile
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./rufans:/rufans
    ports:
      - "3000:3000"
    depends_on:
      - database