version: "3.8"
services:
  # Database: PostgreSQL
  database:
    image: postgres
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  # redis: Redis
  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis:/data
  # Sidekiq
  sidekiq:
    depends_on:
      - 'database'
      - 'redis'
    build:
      context: .
      dockerfile: ./.docker/rufans/Dockerfile
    env_file:
      - ./.secrets/secrets.env
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ./rufans:/rufans
      - '/rufans/tmp' # don't mount tmp directory
  # Anycable
  anycable:
    image: 'anycable/anycable-go:1.0'
    restart: always
    ports:
      - '90:8080'
    env_file:
      - ./.secrets/secrets.env

  # Main project container
  web:
    build:
      context: .
      dockerfile: ./.docker/rufans/Dockerfile
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./rufans:/rufans
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
volumes:
  #db:
  #  driver: local
  redis:
    driver: local