version: "3.8"
services:
  # Database: PostgreSQL
  database:
    image: postgres
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./.docker/volumes/database:/var/lib/postgresql/data
  # Cache: Redis
  cache:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  # Main project container
  web:
    build:
      context: .
      dockerfile: ./.docker/rufans/Dockerfile
    env_file:
      - ./.secrets/secrets.env
    volumes:
      - ./rufans:/rufans
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cache
volumes:
  #db:
  #  driver: local
  cache:
    driver: local